package middleware

import (
	"net/http"

	"github.com/kataras/muxie"
	"golang.org/x/net/context"
)

type resourceType string

// Resource is the context key for requested resource
const Resource = resourceType("resource")

// ResourceGenerator is the type for the function that will generate the resource value
type ResourceGenerator = func(w http.ResponseWriter, r http.Request) string

// WithResource is a middleware used to generate a resource and put it in the context
// for fturue handlers/middlewares to consume it. The resource value is generated by
// the provided function
func WithResource(gen ResourceGenerator) muxie.Wrapper {
	return func(f http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := context.WithValue(r.Context(), Resource, gen(w, *r))
			f.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
