name: build
on: [push]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      - run: yarn install
      - run: yarn build

      - name: Upload quercia build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: __quercia
          path: __quercia

  bundlesize:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: Download previous quercia build
        uses: actions/download-artifact@v1
        with:
          name: __quercia
      - run: yarn install
      - name: Check bundlesize
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        run: yarn bundlewatch

  build:
    needs: frontend
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Download previous quercia build
        uses: actions/download-artifact@v1
        with:
          name: __quercia

      - name: Build pkger asset file
        shell: bash
        run: |
          go get -v -t -d ./...
          go get github.com/markbates/pkger/cmd/pkger
          rm -rf __quercia/*/server
          pkger

      - name: Build the go binary
        run: go build -ldflags="-s -w" -o o2

      - name: Upload prerelease build
        uses: actions/upload-artifact@v2
        with:
          path: ./o2
          name: o2-${{ matrix.platform }}
