name: build
on: [push]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn build

      - name: Upload quercia build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: __quercia
          path: __quercia

  bundlesize:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Download previous quercia build
        uses: actions/download-artifact@v1
        with:
          name: __quercia
      - run: yarn install
      - name: Check bundlesize
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        run: yarn bundlewatch

  build:
    needs: frontend
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download previous quercia build
        uses: actions/download-artifact@v1
        with:
          name: __quercia

      - name: Build pkger asset file
        shell: bash
        run: |
          go get -v -t -d ./...
          go get github.com/markbates/pkger/cmd/pkger
          rm -rf __quercia/*/server
          pkger

      - name: Build the go binary
        run: go build -ldflags="-s -w" -o o2

      - name: Upload prerelease build
        uses: actions/upload-artifact@v2
        with:
          path: ./o2
          name: o2-${{ matrix.platform }}
          uses: docker/build-push-action@v1

  docker:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download previous quercia build
        uses: actions/download-artifact@v1
        with:
          name: __quercia

      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          username: lucat1
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: lucat1/o2
          tags: latest
